#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-hyperscan-soname4
Version  : 4.7.0
Release  : 9
URL      : https://github.com/intel/hyperscan/archive/v4.7.0.tar.gz
Source0  : https://github.com/intel/hyperscan/archive/v4.7.0.tar.gz
Summary  : Intel(R) Hyperscan Library
Group    : Development/Tools
License  : BSD-3-Clause Intel
Requires: compat-hyperscan-soname4-lib = %{version}-%{release}
Requires: compat-hyperscan-soname4-license = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libpcap-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : ragel
# Suppress generation of debuginfo
%global debug_package %{nil}
Patch1: 0001-Update-pcre-version-check.patch
Patch2: 0002-Fixup-distance-symbol-resolution.patch

%description
# Hyperscan
Hyperscan is a high-performance multiple regex matching library. It follows the
regular expression syntax of the commonly-used libpcre library, but is a
standalone library with its own C API.

%package lib
Summary: lib components for the compat-hyperscan-soname4 package.
Group: Libraries
Requires: compat-hyperscan-soname4-license = %{version}-%{release}

%description lib
lib components for the compat-hyperscan-soname4 package.


%package license
Summary: license components for the compat-hyperscan-soname4 package.
Group: Default

%description license
license components for the compat-hyperscan-soname4 package.


%prep
%setup -q -n hyperscan-4.7.0
cd %{_builddir}/hyperscan-4.7.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592616922
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1592616922
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-hyperscan-soname4
cp %{_builddir}/hyperscan-4.7.0/COPYING %{buildroot}/usr/share/package-licenses/compat-hyperscan-soname4/460136879250bc39dbc8be7799af9c079527808f
cp %{_builddir}/hyperscan-4.7.0/LICENSE %{buildroot}/usr/share/package-licenses/compat-hyperscan-soname4/e9e53a0b2358d3fd707a717d971d01ef87bffd0e
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/include/hs/hs.h
rm -f %{buildroot}/usr/include/hs/hs_common.h
rm -f %{buildroot}/usr/include/hs/hs_compile.h
rm -f %{buildroot}/usr/include/hs/hs_runtime.h
rm -f %{buildroot}/usr/lib64/libhs.so
rm -f %{buildroot}/usr/lib64/libhs_runtime.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libhs.pc
rm -f %{buildroot}/usr/share/doc/hyperscan/examples/README.md
rm -f %{buildroot}/usr/share/doc/hyperscan/examples/patbench.cc
rm -f %{buildroot}/usr/share/doc/hyperscan/examples/pcapscan.cc
rm -f %{buildroot}/usr/share/doc/hyperscan/examples/simplegrep.c

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhs.so.4
/usr/lib64/libhs.so.4.7.0
/usr/lib64/libhs_runtime.so.4
/usr/lib64/libhs_runtime.so.4.7.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-hyperscan-soname4/460136879250bc39dbc8be7799af9c079527808f
/usr/share/package-licenses/compat-hyperscan-soname4/e9e53a0b2358d3fd707a717d971d01ef87bffd0e
